services:
  - type: web
    name: vevurn-frontend
    runtime: node
    env: node
    plan: starter
    region: oregon
    rootDir: ./frontend
    buildCommand: |
      echo "=== Frontend Build ==="
      node --version
      npm --version
      npm install
      npm run build
      echo "Build completed, checking output..."
      ls -la .next/
      ls -la .next/standalone/
    startCommand: node .next/standalone/frontend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://vevurn-backend.onrender.com
