services:
- type: web
  name: vevurn-frontend
  runtime: node
  plan: starter
  buildCommand: cd frontend && npm install && npm run build
  startCommand: cd frontend && npm start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_API_URL
    value: https://vevurn-backend.onrender.com
