# Backend and Frontend deployed from their respective directories
services:
  # Backend API Service - Deploy from backend directory
  - type: web
    name: vevurn-backend
    runtime: node
    env: node
    plan: starter
    region: oregon
    rootDir: ./backend
    buildCommand: |
      echo "=== Backend Build from /backend directory ==="
      echo "Node version:" && node --version
      echo "Setting up pnpm..." && corepack enable && corepack prepare pnpm@9.14.4 --activate
      echo "Installing dependencies..." && cd .. && pnpm install --no-frozen-lockfile --ignore-scripts
      echo "Building shared packages..." && pnpm --filter @vevurn/shared build || echo "Shared build skipped"
      echo "Building backend..." && pnpm --filter @vevurn/backend build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: vevurn-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: vevurn-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        value: https://vevurn-backend.onrender.com
      - key: FRONTEND_URL
        value: https://vevurn-frontend.onrender.com
    healthCheckPath: /health

  # Frontend Next.js Service - Deploy from frontend directory  
  - type: web
    name: vevurn-frontend
    runtime: node
    env: node
    plan: starter
    region: oregon
    rootDir: ./frontend
    buildCommand: |
      echo "=== Frontend Build from /frontend directory ==="
      node --version
      corepack enable
      corepack prepare pnpm@9.14.4 --activate
      cd ..
      pnpm install --no-frozen-lockfile
      pnpm --filter @vevurn/shared build
      pnpm --filter frontend build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://vevurn-backend.onrender.com
      - key: BETTER_AUTH_URL
        value: https://vevurn-backend.onrender.com
      - key: BETTER_AUTH_SECRET
        fromService:
          type: web
          name: vevurn-backend
          envVarKey: BETTER_AUTH_SECRET

# Database Configuration
databases:
  - name: vevurn-postgres
    plan: starter
    databaseName: vevurn_pos
    user: vevurn_user

# Redis Configuration  
services:
  - type: redis
    name: vevurn-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVICE_TYPE
        value: backend
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: vevurn-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: vevurn-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        value: https://vevurn-backend.onrender.com
      - key: FRONTEND_URL
        value: https://vevurn-frontend.onrender.com
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
    healthCheckPath: /health
    
  # Frontend Next.js Service  
  - type: web
    name: vevurn-frontend
    env: node
    region: oregon
    rootDir: ./
    plan: starter
    buildCommand: pnpm run frontend:build
    startCommand: |
      cd frontend
      corepack enable
      corepack prepare pnpm@9.14.4 --activate
      pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVICE_TYPE
        value: frontend
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://vevurn-backend.onrender.com
      - key: BETTER_AUTH_URL
        value: https://vevurn-backend.onrender.com
      - key: BETTER_AUTH_SECRET
        fromService:
          type: web
          name: vevurn-backend
          envVarKey: BETTER_AUTH_SECRET

# Database Configuration
databases:
  - name: vevurn-postgres
    plan: starter # Change to 'standard' for production
    databaseName: vevurn_pos
    user: vevurn_user

# Redis Configuration  
services:
  - type: redis
    name: vevurn-redis
    plan: starter # Change to 'standard' for production
    maxmemoryPolicy: allkeys-lru
