global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vevurn-pos'
    replica: 'A'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'vevurn-pos'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
