apiVersion: v1
kind: Namespace
metadata:
  name: vevurn
  labels:
    name: vevurn
    environment: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vevurn-backend
  namespace: vevurn
  labels:
    app: vevurn-backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vevurn-backend
  template:
    metadata:
      labels:
        app: vevurn-backend
    spec:
      containers:
      - name: backend
        image: vevurn/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vevurn-backend-service
  namespace: vevurn
spec:
  selector:
    app: vevurn-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vevurn-frontend
  namespace: vevurn
  labels:
    app: vevurn-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vevurn-frontend
  template:
    metadata:
      labels:
        app: vevurn-frontend
    spec:
      containers:
      - name: frontend
        image: vevurn/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.vevurn.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vevurn-frontend-service
  namespace: vevurn
spec:
  selector:
    app: vevurn-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vevurn-ingress
  namespace: vevurn
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - vevurn.com
    - api.vevurn.com
    secretName: vevurn-tls
  rules:
  - host: vevurn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vevurn-frontend-service
            port:
              number: 80
  - host: api.vevurn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vevurn-backend-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vevurn-backend-hpa
  namespace: vevurn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vevurn-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vevurn-frontend-hpa
  namespace: vevurn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vevurn-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
